name: base_celery
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.6
  - redis-py=3.3.4
  - celery=4.2.1
  - flower=0.9.2
  - tornado=5.0.1
  - rasterio=1.0.24
  - gdal
  - numpy
  - pandas
  - psycopg2
  - scipy
  - requests