name: flood_base
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - flask
  - flask-cors
  - requests
  - beautifulsoup4
  - lxml
  - redis-py
  - celery
  - psycopg2
  - gunicorn
  - flask-babel